/** THIS FILE IS AUTOGENERATED, DO NOT EDIT IT! */
import * as Types from '../../types';

import gql from 'graphql-tag';
import * as Urql from 'urql';
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
export type UpdateProfileMutationVariables = Types.Exact<{
  input: Types.UpdateProfileInput;
}>;


export type UpdateProfileMutation = { readonly __typename?: 'Mutation', readonly updateProfile: { readonly __typename?: 'UpdateProfilePayload', readonly profile: { readonly __typename?: 'Profile', readonly id: number, readonly fullName: string | null, readonly userId: string } } };


export const UpdateProfileDocument = gql`
    mutation UpdateProfile($input: UpdateProfileInput!) {
  updateProfile(input: $input) {
    profile {
      id
      fullName
      userId
    }
  }
}
    `;

export function useUpdateProfileMutation() {
  return Urql.useMutation<UpdateProfileMutation, UpdateProfileMutationVariables>(UpdateProfileDocument);
};