/** THIS FILE IS AUTOGENERATED, DO NOT EDIT IT! */
import * as Types from '../../types';

import gql from 'graphql-tag';
import * as Urql from 'urql';
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
export type DeleteFocusItemMutationVariables = Types.Exact<{
  input: Types.DeleteFocusItemInput;
}>;


export type DeleteFocusItemMutation = { readonly __typename?: 'Mutation', readonly deleteFocusItem: { readonly __typename?: 'DeleteFocusItemOutput', readonly success: boolean } };


export const DeleteFocusItemDocument = gql`
    mutation DeleteFocusItem($input: DeleteFocusItemInput!) {
  deleteFocusItem(input: $input) {
    success
  }
}
    `;

export function useDeleteFocusItemMutation() {
  return Urql.useMutation<DeleteFocusItemMutation, DeleteFocusItemMutationVariables>(DeleteFocusItemDocument);
};